default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: staff_development

test:
  <<: *default
  database: staff_test

production:
  <<: *default
  database: staff_production
  username: staff
  password: <%= ENV['OVERTIME_DATABASE_PASSWORD'] %>
